version: '3.9'
services:
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data:rw
    ports:
      - '6379:6379'

  app:
    image: node:alpine
    restart: always
    ports:
      - '8080:3000'
    depends_on:
      - redis
    working_dir: /usr/src/app
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm run start:dev"

volumes:
  redis-data:
